api:
  base_url: "https://alphapi.aip.sharif.ir/v1/chat/completions"
  api_key: "sk-***"

models:
  vision: "DeepSeek-OCR"
  text: "gemma-3-27b-it"

paths:
  input_pdfs: "input_pdfs"
  output_raw: "output_raw"
  output_texts: "output_texts"
  temp_images: "temp_images"

processing:
  dpi: 300 
  sequentiol: treu
  max_retry: 5
  retry_delay: 10  #seconds

